name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # หรือ branch ที่คุณต้องการ deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.8.0 # หรือเวอร์ชัน Node.js ที่คุณใช้

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets. FIREBASE_SERVICE_ACCOUNT_RECIPE_SHARING_46DBD }}' # เปลี่ยนเป็นชื่อ secret ของคุณ
          channelId: live # หรือ channel ที่คุณต้องการ deploy (live หรือ preview)
          projectId: recipe-sharing-46dbd # เปลี่ยนเป็น Project ID ของ Firebase ของคุณ
